<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-6BCATAP" ignored="0" name="Test" tests="2" failures="1" timestamp="10 Mar 2018 09:46:26 GMT" time="0.043" errors="0">
  <testcase name="dummy_test_to_fail" time="0.014" classname="test.test">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at test.test.dummy_test_to_fail(test.java:14)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- dummy_test_to_fail -->
  <testcase name="dummy_test_to_pass" time="0.001" classname="test.test"/>
</testsuite> <!-- Test -->
